### ISSUE TITLE
服务器启动报错

### ISSUE THREAD

**Issue by wanglitongtong** [GameFrameX/GameFrameX.Server#1]
7.22 更新后，服务器启动报错
[17:34:21 ERR] System.NullReferenceException: Object reference not set to an instance of an object.
   at GameFrameX.Core.Components.ComponentRegister.ActiveComps(IActor actor, Func`2 predict)
   at GameFrameX.Core.Actors.Impl.ActionAsyncWrapper.DoTask()

**Comment by AlianBlank** [comment]
已经修复了.请重新拉取新的代码
